FPS = 60

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 640
MAP_WIDTH = SCREEN_WIDTH * 3
MAP_HEIGHT = SCREEN_HEIGHT * 3

TILESIZE = 8
GRIDWIDTH = int(SCREEN_WIDTH / TILESIZE)
GRIDHEIGHT = int(SCREEN_HEIGHT / TILESIZE)
MAPGRIDWIDTH = int(MAP_WIDTH / TILESIZE)
MAPGRIDHEIGHT = int(MAP_HEIGHT / TILESIZE)

# Player
PLAYER_START_POS = [int(MAPGRIDWIDTH / 2), int(MAPGRIDHEIGHT / 2)]
PLAYER_SPEED = TILESIZE

# Colours
WHITE = (255, 255, 255)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
BLACK = (0, 0, 0, 255)
GRAY = (128, 128, 128, 255)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)
DARKGREEN = (51, 102, 0, 255)
LIGHTBLUE = (0, 255, 255)

SCREEN_COL = BLACK
BACKGROUND_COL = DARKGREEN
GRIDLINE_COL = WHITE
PLAYER_COL = LIGHTBLUE
COIN_COL = YELLOW
ENEMY_COL = RED
WALL_COL = GRAY
BULLET_COL = GREEN

# Map
MAX_TUNNELS = 25000
MAX_LENGTH = 2
TUNNEL_WIDTH = 3

# Sprites
N_COINS = 5
COIN_CLUSTERS = 5
N_ENEMIES = 5
SPAWN_GAP = 1
SPAWN_DIST = 25
SPAWN_DIST_COINS = 15
SPAWN_DIST_ENEMIES = 15

# AI
BOT_DELAY = 70

# Coin seed
COIN_SEED = 8

# A-Start fix variable
END_PREVIOUS = 0